web:
    build: .
    ports:
      - 8443:8443
    volumes:
      - .:/usr/app
    links:
      - db
    environment:
      SPRING_DATASOURCE_URL: db
      SPRING_DATASOURCE_USERNAME: growingUser
      SPRING_DATASOURCE_PASSWORD: dawEquipo3-2021
db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: dawEquipo3-2021
  expose:
    - 3306