web:
    build: .
    ports:
      - 8443:8443
    links:
      - db
db:
  image: mysql
  restart: always
  healthcheck:
    test: "/usr/bin/mysql --user=root --password=password--execute \"SHOW DATABASES;\""
    interval: 2s
    timeout: 20s
    retries: 10
  environment:
    MYSQL_ROOT_PASSWORD: dawEquipo3-2021
  ports:
    - 3306:3306