version: '3'

services:

  db:
    image: mysql:latest
    container_name: growing_db
    restart: always
    environment:
      - MYSQL_DATABASE=growing
      - MYSQL_ROOT_PASSWORD=dawEquipo3-2021

  web:
    image: dawequipo3/growing:latest
    ports:
      - 8443:8443
    container_name: growing
    restart: always
    links:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/growing
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=dawEquipo3-2021
